function openNav6() 
{
    document.getElementById("myNav6").style.display = "block";
}
  
function closeNav6() 
{
    document.getElementById("myNav6").style.display = "none";
}


function openNav5() 
{
    document.getElementById("myNav5").style.display = "block";
}
  
function closeNav5() 
{
    document.getElementById("myNav5").style.display = "none";
}


function openNav4() 
{
    document.getElementById("myNav4").style.display = "block";
}
  
function closeNav4() 
{
    document.getElementById("myNav4").style.display = "none";
}


function openNav3() 
{
    document.getElementById("myNav3").style.display = "block";
}
  
function closeNav3() 
{
    document.getElementById("myNav3").style.display = "none";
}

function openNav2() 
{
    document.getElementById("myNav2").style.display = "block";
}
  
function closeNav2() 
{
    document.getElementById("myNav2").style.display = "none";
}
  
function openNav1() 
{
    document.getElementById("myNav1").style.display = "block";
}
  
function closeNav1() 
{
    document.getElementById("myNav1").style.display = "none";
}