<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EDUCATIONAL BACKGROUND</title>
        <link rel="icon" type="image/x-icon" href="../IMAGES/PESO_LOGO.png">
        <link rel="stylesheet" href="../CSS/PERSONAL_INFORMATION.CSS">
        <link rel="stylesheet" href="../CSS/NAVBAR.CSS">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        
    </head>

    <body>

        <div class="sidenav">
            <a href="#" class="noHover" style="height: 100px;">
                <img src="../IMAGES/LOGO.png"  style="width:200px;height:60px; float: left; margin-left: 30px;">
            </a>
            
            <a href="#">HOME</a>
            <a href="#">APPLICANTS</a>
            <a href="#" class="active">JOB POSTS</a>
            <a href="#">JOB POSTING</a>
            <a href="#">NOTIFICATION</a>
            <a href="#">PROFILE</a>
            <a href="#">SETTING</a>
            <a href="#">MORE INFO</a>
            <a href="#">LOG OUT</a>
          </div>
          
          <div class="main">
            <div id="navbar">
                <a class="active" style="width: 350px; text-align: left;" href="#">Home</a>
                <a style="width: 350px; padding-top: 20px; margin-left: 80px;">
                    <formsearch class="example" action="action_page.php">
                      <center>
                      <input type="text" placeholder="" name="search">
                      <button type="submit"><i class="fa fa-search"></i></button>
                      </center>
                      
                  </formsearch>
                  </a>
                  
                <a href="#"></a>
              </div>
              
              <div class="content">
                <div class="row">
                    <div class="column side">
                      <div class="card1">
                        <center>
                        <img style="height:120px; width:120px; border-radius: 50%; margin-top: 10px;" src="../IMAGES/SAMPLE_PROFILE.jpg">
                        <br>
                        <button type="" class="update" name="">UPDATE PROFILE</button>
                      </center>
                      <br>
                        <a href="#" class="active">PERSONAL INFORMATION</a>
                        <a href="#">EDUCATIONAL BACKGROUND</a>
                        <a href="#">JOB PREFERENCE</a>
                        <a href="#">TRAININGS</a>
                        <a href="#">ELIGIBILITY</a>
                        <a href="#">WORK EXPERIENCES</a>
                        <a href="#">SKILLS</a>
                        <a href="#">AUTHORIZATION</a>
                      
                      </div>
                    </div>
                    
                    <div class="column middle">
                      <div class="card2">
                        <h1>EDUCATIONAL BACKGROUND</h1>
                    
                        <div class="card3A" style="height:40px">
                          <div class="col1" style="width: 65%">
                          <h2>CURRENTLY IN SCHOOL?</h2>
                          </div>
                          <div class="col2" style="width: 30%">
                            <input style="margin-top: 10px;" type="text" name="" value="">
                            </div>
                        </div>

                        <div class="card3A">
                          <div class="col3">
                          <h2>HIGHEST EDUCATIONAL LEVEL</h2>
                          <input type="text" name="" value="">
                          </div>
                        </div>

                        <div class="card3A">
                          <div class="col3">
                          <h2>YEAR GRADUATED/LAST YEAR ATTENDED</h2>
                          <input type="text" name="" value="">
                          </div>
                        </div>

                        <div class="card3A">
                          <div class="col3">
                          <h2>SCHOOL/UNIVERSITY</h2>
                          <input type="text" name="" value="">
                          </div>
                        </div>
                        
                        <div class="card3A">
                          <div class="col3">
                          <h2>COURSE/PROGRAM</h2>
                          <input type="text" name="" value="">
                          </div>
                        </div>
                        
                        <div class="card3A">
                          <div class="col3">
                          <h2>AWARDS/HONORS RECEIVED</h2>
                          <input type="text" name="" value="">
                          </div>
                        </div>

                      </div>
                    
                        
                      
                    </div>
                    
                   
                  </div>
              
          </div>

          <script src="../JS/NAVBAR.JS"></script>
    </body>

</html>