<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EDUCATIONAL BACKGROUND</title>
        <link rel="icon" type="image/x-icon" href="../IMAGES/PESO_LOGO.png">
        <link rel="stylesheet" href="../CSS/TRAININGS.CSS">
        <link rel="stylesheet" href="../CSS/NAVBAR.CSS">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        
    </head>

    <body>

        <div class="sidenav">
            <a href="#" class="noHover" style="height: 100px;">
                <img src="../IMAGES/LOGO.png"  style="width:200px;height:60px; float: left; margin-left: 30px;">
            </a>
            
            <a href="#">HOME</a>
            <a href="#">APPLICANTS</a>
            <a href="#" class="active">JOB POSTS</a>
            <a href="#">JOB POSTING</a>
            <a href="#">NOTIFICATION</a>
            <a href="#">PROFILE</a>
            <a href="#">SETTING</a>
            <a href="#">MORE INFO</a>
            <a href="#">LOG OUT</a>
          </div>
          
          <div class="main">
            <div id="navbar">
                <a class="active" style="width: 350px; text-align: left;" href="#">Home</a>
                <a style="width: 350px; padding-top: 20px; margin-left: 80px;">
                    <formsearch class="example" action="action_page.php">
                      <center>
                      <input type="text" placeholder="" name="search">
                      <button type="submit"><i class="fa fa-search"></i></button>
                      </center>
                      
                  </formsearch>
                  </a>
                  
                <a href="#"></a>
              </div>
              
              <div class="content">
                <div class="row">
                    <div class="column side">
                      <div class="card1">
                        <center>
                        <img style="height:120px; width:120px; border-radius: 50%; margin-top: 10px;" src="../IMAGES/SAMPLE_PROFILE.jpg">
                        <br>
                        <button type="" class="update" name="">UPDATE PROFILE</button>
                      </center>
                      <br>
                      <a href="#" class="active">PERSONAL INFORMATION</a>
                        <a href="#">JOB PREFERENCE</a>
                        <a href="#">EDUCATIONAL BACKGROUND</a>
                        <a href="#">TRAININGS</a>
                        <a href="#">ELIGIBILITY</a>
                        <a href="#">WORK EXPERIENCES</a>
                        <a href="#">SKILLS</a>
                        <a href="#">AUTHORIZATION</a>
                      
                      </div>
                    </div>
                    
                    <div class="column middle">
                      <div class="card2">
                        <h1>ELIGIBILITY</h1>

                   

                    <div class="card3">
                            <table style="width:100%">
                                <center>
                                <tr>
                                    <th>
                                        <h2>CAREER SERVICE/ BOARD/ BAR</h2>
                                    </th>
                                    <th style=width:200px;>
                                        <h2>LICENSE NUMBER</h2>
                                    </th>
                                    <th style=width:150px;>
                                        <h2>EXPIRY DATE</h2>
                                    </th>
                                </tr>

                                <tr>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                </tr>

                                <tr>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                </tr>

                                <tr>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                    <td>
                                        <input style=width:100%;float:left; type="text" name="" placeholder="" required maxlength="50">
                                    </td>
                                </tr>

                                

                                
                                </center>
                            </table>
                    </div>
                    <div class="card5">
                    <h5>LANGUAGE PROFECIENCY CERTIFICATION</h5>
                    <h6>
                                        <input type="checkbox" id="cert_1" name="languageCertifications[]" value="IELTS">
                                        <label for="cert_1">International English Language Testing System (IELTS)</label><br>
                                        <input type="checkbox" id="cert_2" name="languageCertifications[]" value="TOEFL">
                                        <label for="cert_2">Test of English as a Foreign Language (TOEFL)</label><br>
                                        <input type="checkbox" id="cert_3" name="languageCertifications[]" value="TOCFL">
                                        <label for="cert_3">Test of Chinese as a Foreign Language (TOCFL)</label><br>
                                        <input type="checkbox" id="cert_4" name="languageCertifications[]" value="JLPT">
                                        <label for="cert_4">Japanese Language Proficiency Test (JLPT)</label><br>
                                        <input type="checkbox" id="cert_5" name="languageCertifications[]" value="TOPIC">
                                        <label for="cert_5">Test of Proficiency in Korea (TOPIC)</label><br>
                                        <input type="checkbox" id="cert_other" name="cert_other" value="">
                                        <label for="otherCertification">Other:</label>
                                        <input style="width: 20%; height: 15px;" type="text" id="otherCertification" name="otherCertification" value="" maxlength="50">
                    </h6>

                    </div>

                    <div class="card4" style="height:40px">
                            <div class="col1" style="width: 65%">
                                <h4>ARE YOU A 4Ps BENEFICIERY?</h4>
                            </div>
                            <div class="col2" style="width: 30%">
                                <input style="margin-top: 15px;" type="text" name="" value="">
                            </div>
                    </div>
                        <br>

                        <div class="card5">
                    <h5>DIALECTS SPOKEN</h5>
                    <h6>
                    <input type="checkbox" id="Tagalog" name="dialectsSpoken[]" value="Tagalog">
                                        <label for="dialect_1">Tagalog</label><br>
                                        <input type="checkbox" id="Ilocano" name="dialectsSpoken[]" value="Ilocano">
                                        <label for="dialect_2">Ilocano</label><br>
                                        <input type="checkbox" id="Ilonggo" name="dialectsSpoken[]" value="Ilonggo">
                                        <label for="dialect_3">Ilonggo</label><br>
                                        <input type="checkbox" id="Bikol" name="dialectsSpoken[]" value="Bikol">
                                        <label for="dialect_4">Bikol</label><br>
                                        <input type="checkbox" id="dialect_other" name="dialectsSpoken[]r" value="">
                                        <label for="dialect_other">Other:</label>
                                        <input style="width: 20%; height: 15px;" type="text" id="dialect_other" name="otherDialect" value="" maxlength="50">
                    </h6>

                    </div>

                    </div>

                    
                    
                        
                      
                    </div>
                    
                   
                  </div>
              
          </div>

          <script src="../JS/NAVBAR.JS"></script>
    </body>

</html>