<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EDUCATIONAL BACKGROUND</title>
        <link rel="icon" type="image/x-icon" href="../IMAGES/PESO_LOGO.png">
        <link rel="stylesheet" href="../CSS/JOB_PREFERENCE.CSS">
        <link rel="stylesheet" href="../CSS/NAVBAR.CSS">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        
    </head>

    <body>

        <div class="sidenav">
            <a href="#" class="noHover" style="height: 100px;">
                <img src="../IMAGES/LOGO.png"  style="width:200px;height:60px; float: left; margin-left: 30px;">
            </a>
            
            <a href="#">HOME</a>
            <a href="#">APPLICANTS</a>
            <a href="#" class="active">JOB POSTS</a>
            <a href="#">JOB POSTING</a>
            <a href="#">NOTIFICATION</a>
            <a href="#">PROFILE</a>
            <a href="#">SETTING</a>
            <a href="#">MORE INFO</a>
            <a href="#">LOG OUT</a>
          </div>
          
          <div class="main">
            <div id="navbar">
                <a class="active" style="width: 350px; text-align: left;" href="#">Home</a>
                <a style="width: 350px; padding-top: 20px; margin-left: 80px;">
                    <formsearch class="example" action="action_page.php">
                      <center>
                      <input type="text" placeholder="" name="search">
                      <button type="submit"><i class="fa fa-search"></i></button>
                      </center>
                      
                  </formsearch>
                  </a>
                  
                <a href="#"></a>
              </div>
              
              <div class="content">
                <div class="row">
                    <div class="column side">
                      <div class="card1">
                        <center>
                        <img style="height:120px; width:120px; border-radius: 50%; margin-top: 10px;" src="../IMAGES/SAMPLE_PROFILE.jpg">
                        <br>
                        <button type="" class="update" name="">UPDATE PROFILE</button>
                      </center>
                      <br>
                        <a href="#" class="active">PERSONAL INFORMATION</a>
                        <a href="#">EDUCATIONAL BACKGROUND</a>
                        <a href="#">JOB PREFERENCE</a>
                        <a href="#">TRAININGS</a>
                        <a href="#">ELIGIBILITY</a>
                        <a href="#">WORK EXPERIENCES</a>
                        <a href="#">SKILLS</a>
                        <a href="#">AUTHORIZATION</a>
                      
                      </div>
                    </div>
                    
                    <div class="column middle">
                      <div class="card2">
                        <h1>JOB PREFERENCE</h1>
                        <div class="card3">
                        <table style="width:100%">
                                            <center>
                                            <tr>
                                                <th><h2>PREFERRED OCCUPATION</h2>
                                                    <h3>(e.g., clerk, call center agent, saleslady)</h3>
                                                </th>
                                                <th><h2>PREFERRED INDUSTRY</h2>
                                                    <h3>(e.g., IY-BPM, construction, manufacturing)</h3>
                                                </th>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <input style=width:100%;float:left; type="text" name="occupation1" placeholder="PREFERRED OCCUPATION #1" required maxlength="50">
                                                </td>
                                                <td>
                                                    <input style=width:100%;float:left; type="text" name="industry1" placeholder="PREFERRED INDUSTRY #1" required maxlength="50">
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <input style=width:100%;float:left; type="text" name="occupation2" placeholder="PREFERRED OCCUPATION #2" required maxlength="50">
                                                </td>
                                                <td>
                                                    <input style=width:100%;float:left; type="text" name="industry2" placeholder="PREFERRED INDUSTRY #2" required maxlength="50">
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <input style=width:100%;float:left; type="text" name="occupation3" placeholder="PREFERRED OCCUPATION #3" required maxlength="50">
                                                </td>
                                                <td>
                                                    <input style=width:100%;float:left; type="text" name="industry3" placeholder="PREFERRED INDUSTRY #3" required maxlength="50">
                                                </td>
                                            </tr>
                                            </center>
        
                                            
        
                    </table>
                    </div>

                    <div class="card4" style="height:40px">
                          <div class="col1" style="width: 65%">
                          <h4>ARE YOU A 4Ps BENEFICIERY?</h4>
                          </div>
                          <div class="col2" style="width: 30%">
                            <input style="margin-top: 15px;" type="text" name="" value="">
                            </div>
                    </div>

                    <div class="card5">
                          <div class="col3">
                          <input type="text" name="" value="">
                          </div>
                    </div>
                    
                    <div class="card5">
                          <div class="col3">
                          <input type="text" name="" value="">
                          </div>
                    </div>

                      </div>
                    
                        
                      
                    </div>
                    
                   
                  </div>
              
          </div>

          <script src="../JS/NAVBAR.JS"></script>
    </body>

</html>