<!-- VERSION 3 -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>PERSONAL INFORMATION</title>
        <link rel="icon" type="image/x-icon" href="../IMAGES/PESO_LOGO.png">
        <link rel="stylesheet" href="../CSS/PERSONAL_INFORMATION.CSS">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="../JS/loader.js"></script>
        
    </head>

    <body>
          <div class="loader"><div></div><div></div><div></div><div></div></div>
        
          <?php
          include 'function.php';
          include 'sidebar.php';
          ?>
            <div class="main">
              <div class="content">
                <div class="row">
                    <div class="column side">
                      <div class="">
                      <a href="">Personal Information</a>
                      <a href="">Educational Background</a>
                      <a href="">Job Preference</a>
                      <a href=""> Trainings</a>
                      <a href="">Eligibility</a>
                      <a href="">Work Experiences</a>
                      <a href="">Skills</a>
                      <a href="">Authorization</a>
                      </div>
                        
                    </div>
                    
                    <div class="column middle">
                      

                    </div>
                      
                    </div>
                    
                   
                  </div>
              
          </div>

          <script src="../JS/NAVBAR.JS"></script>
    </body>

</html>