<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APPLICANT LOGIN</title>
    <link rel="icon" type="image/x-icon" href="../IMAGES/PESO_LOGO.png">
    <link rel="stylesheet" href="../CSS/PESO_HOMEPAGE.CSS">
  </head>

  <body>
    <div class="header" id="myHeader">
      <a href="#" style="width: 55%; margin-left: 20px;"><img src="../IMAGES/LOGO.png"  style="width:300px;height:90px; float: left; margin-left: 30px;"></a>
    </div>
    <center>
    <!-- -------------------- BUTTONSSSSSS --------------------- -->
    <div class="card1">
      <a href="APPLICANT_ACCESS.PHP"><button class="btn"><i><img src="../IMAGES/APPLICANTS.png" style="height: 70px; width: 70px"></i><br>APPLICANTS</button></a>
      <a href="COMPANY_ACCESS.PHP"><button class="btn"><i><img src="../IMAGES/COMPANIES.png" style="height: 70px; width: 70px"></i><br>COMPANIES</button></a>
      <a href="JOBPOSTING_ACCESS.PHP"><button class="btn"><i><img src="../IMAGES/JOBPOSTING.png" style="height: 70px; width: 70px"></i><br>JOB POSTING</button></a>
      <br> <br> <br> <br>
      <a href="DATABASE_ACCESS.PHP"><button class="btn"><i><img src="../IMAGES/DATABASE.png" style="height: 70px; width: 70px"></i><br>DATABASE</button></a>
      <a href="REPORT_ACCESS.PHP"><button class="btn"><i><img src="../IMAGES/REPORTS.png" style="height: 70px; width: 70px"></i><br>REPORTS</button></a>
      <a href="PESO_POLICIES.PHP"><button class="btn"><i><img src="../IMAGES/POLICIES.png" style="height: 70px; width: 70px"></i><br>POLICIES</button></a>
    </div>
    </center>


    
    

    <script src="../JS/PESO_HOMEPAGE.JS"></script>
  </body>
</html>