<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APPLICANT LOGIN</title>
    <link rel="icon" type="image/x-icon" href="../IMAGES/PESO_LOGO.png">
    <link rel="stylesheet" href="../CSS/PESO_HOMEPAGE.CSS">
   
  </head>

  <body>
    <div class="header" id="myHeader">
      <a href="#" style="width: 55%; margin-left: 20px;"><img src="../IMAGES/LOGO.png"  style="width:300px;height:90px; float: left; margin-left: 30px;"></a>
    </div>
             
    <center>
        <div class="card1">
        <a href="#"><button class="register">APPLICANTS</button></a>
        <a href="#"><button class="register">JOB POSTING</button></a>
        <a href="#"><button class="register">COMPANY</button></a>
        <a href="#"><button class="register">DATABASE</button></a>
        <a href="#"><button class="register">REPORTS</button></a>
        <a href="#"><button class="register">POLICIES</button></a>

        </div>
    </center>