<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APPLICANT LOGIN</title>
    <link rel="icon" type="image/x-icon" href="../IMAGES/PESO_LOGO.png">
    <link rel="stylesheet" href="../CSS/PESO_HOMEPAGE.CSS">
    

   
  </head>

  <body>
    <div class="header" id="myHeader">
      <a href="#" style="width: 55%; margin-left: 20px;"><img src="../IMAGES/LOGO.png"  style="width:300px;height:90px; float: left; margin-left: 30px;"></a>
    </div>
    <center>
    <!-- -------------------- BUTTONSSSSSS --------------------- -->
    <div class="card1">
      <button class="btn"><span onclick="openNav1()"><i><img src="../IMAGES/APPLICANTS.png" style="height: 70px; width: 70px"></i><br>APPLICANTS</span></button>
      <button class="btn"><span onclick="openNav2()"><i><img src="../IMAGES/COMPANIES.png" style="height: 70px; width: 70px"></i><br>COMPANIES</span></button>
      <button class="btn"><span onclick="openNav3()"><i><img src="../IMAGES/JOBPOSTING.png" style="height: 70px; width: 70px"></i><br>JOB POSTING</span></button>
      <br> <br> <br> <br>
      <button class="btn"><span onclick="openNav4()"><i><img src="../IMAGES/DATABASE.png" style="height: 70px; width: 70px"></i><br>DATABASE</span></button>
      <button class="btn"><span onclick="openNav5()"><i><img src="../IMAGES/REPORTS.png" style="height: 70px; width: 70px"></i><br>REPORTS</span></button>
      <button class="btn"><span onclick="openNav6()"><i><img src="../IMAGES/POLICIES.png" style="height: 70px; width: 70px"></i><br>POLICIES</span></button>
    </div>
    </center>


    <!-- -------------------- MODALSSSSSS --------------------- -->
    <!-- APPLICANTS -->
    <div id="myNav1" class="overlay">
      <center>
        <div class="overlay-content">         
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav1()">&times;</a>
          <h1>APPLICANTS</h1>

          <div class="card2">
            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMAIL" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMPLOYEE NUMBER" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="password" placeholder="PASSCODE" name="" id="password"required maxlength="20">
              </div>
            </div>
                                        
            <div class="card4">
              <br>
              <center><button type="submit" class="login" name="submit">ACCESS</button></center>
              <br>
            </div>
          </div>
        </div>
      </center>
    </div>

    <!-- COMPANIES -->
    <div id="myNav2" class="overlay">
      <center>
        <div class="overlay-content">         
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav2()">&times;</a>
          <h1>COMPANIES</h1>

          <div class="card2">
            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMAIL" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMPLOYEE NUMBER" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="password" placeholder="PASSCODE" name="" id="password"required maxlength="20">
              </div>
            </div>
                                        
            <div class="card4">
              <br>
              <center><button type="submit" class="login" name="submit">ACCESS</button></center>
              <br>
            </div>
          </div>
        </div>
      </center>
    </div>

    <!-- JOB POSTING -->
    <div id="myNav3" class="overlay">
      <center>
        <div class="overlay-content">         
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav3()">&times;</a>
          <h1>JOB POSTING</h1>

          <div class="card2">
            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMAIL" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMPLOYEE NUMBER" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="password" placeholder="PASSCODE" name="" id="password"required maxlength="20">
              </div>
            </div>
                                        
            <div class="card4">
              <br>
              <center><button type="submit" class="login" name="submit">ACCESS</button></center>
              <br>
            </div>
          </div>
        </div>
      </center>
    </div>

    <!-- DATABASE -->
    <div id="myNav4" class="overlay">
      <center>
        <div class="overlay-content">         
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav4()">&times;</a>
          <h1>DATABASE</h1>

          <div class="card2">
            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMAIL" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMPLOYEE NUMBER" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="password" placeholder="PASSCODE" name="" id="password"required maxlength="20">
              </div>
            </div>
                                        
            <div class="card4">
              <br>
              <center><button type="submit" class="login" name="submit">ACCESS</button></center>
              <br>
            </div>
          </div>
        </div>
      </center>
    </div>

    <!-- REPORTS -->
    <div id="myNav5" class="overlay">
      <center>
        <div class="overlay-content">         
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav5()">&times;</a>
          <h1>REPORTS</h1>

          <div class="card2">
            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMAIL" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMPLOYEE NUMBER" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="password" placeholder="PASSCODE" name="" id="password"required maxlength="20">
              </div>
            </div>
                                        
            <div class="card4">
              <br>
              <center><button type="submit" class="login" name="submit">ACCESS</button></center>
              <br>
            </div>
          </div>
        </div>
      </center>
    </div>
    
    <!-- POLICIES -->
    <div id="myNav6" class="overlay">
      <center>
        <div class="overlay-content">         
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav6()">&times;</a>
          <h1>POLICIES</h1>

          <div class="card2">
            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMAIL" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="text" placeholder="EMPLOYEE NUMBER" name="" required>
              </div>
            </div>

            <div class="card3">
              <div class="col1">
                <input type="password" placeholder="PASSCODE" name="" id="password"required maxlength="20">
              </div>
            </div>
                                        
            <div class="card4">
              <br>
              <center><button type="submit" class="login" name="submit">ACCESS</button></center>
              <br>
            </div>
          </div>
        </div>
      </center>
    </div>

    

    <script src="../JS/PESO_HOMEPAGE.JS"></script>
  </body>
</html>