<!-- VERSION 3 -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>APPLICANT HOMEPAGE</title>
        <link rel="icon" type="image/x-icon" href="../IMAGES/PESO_LOGO.png">
        <link rel="stylesheet" href="../CSS/ACCESS_REGISTER.CSS">
        <link rel="stylesheet" href="../CSS/NAVBAR.CSS">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        
    </head>

    <body>

        <div class="sidenav">
            <a href="#" class="noHover" style="height: 100px;">
                <img src="../IMAGES/LOGO.png"  style="width:200px;height:60px; float: left; margin-left: 30px;">
            </a>
            
            <a href="#">HOME</a>
            <a href="#" class="active">ACCESS</a>
            <a href="#">PESO REGISTER</a>
            <a href="#">JOB POSTS</a>
            <a href="#">REPORTS</a>
            <a href="#">PROFILE</a>
            <a href="#">SETTING</a>
            <a href="#">MORE INFO</a>
            <a href="#">LOG OUT</a>
        </div>
          
        <div class="main">
            <div id="navbar">
                <a class="active" style="width: 500px; text-align: left;" href="#">REGISTER PESO ACCESS</a>
                <a href="#"></a>
            </div>
                
            <div class="content">
                <div class="card1">
                    <a href=""><button class="btn"><i><img src="../IMAGES/APPLICANTS.png" style="height: 70px; width: 70px"></i><br>APPLICANTS</button></a>
                    <a href=""><button class="btn"><i><img src="../IMAGES/COMPANIES.png" style="height: 70px; width: 70px"></i><br>COMPANIES</button></a>
                    <a href=""><button class="btn"><i><img src="../IMAGES/JOBPOSTING.png" style="height: 70px; width: 70px"></i><br>JOB POSTING</button></a>
                    <br> <br> <br> <br>
                    <a href=""><button class="btn"><i><img src="../IMAGES/DATABASE.png" style="height: 70px; width: 70px"></i><br>DATABASE</button></a>
                    <a href=""><button class="btn"><i><img src="../IMAGES/REPORTS.png" style="height: 70px; width: 70px"></i><br>REPORTS</button></a>
                    <a href=""><button class="btn"><i><img src="../IMAGES/POLICIES.png" style="height: 70px; width: 70px"></i><br>POLICIES</button></a>
                </div>
                            
                            
            </div>
        
        </div>


        <script src="../JS/APPLICANT_REGISTER.JS"></script>
        <script src="../JS/NAVBAR.JS"></script>
    </body>

</html>

